server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: Users
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/users/**
            - Method=GET,POST,PUT,DELETE
        - id: localisation
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/localisations/**